name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装pnpm
        uses: pnpm/action-setup@v6
        id: pnpm-install
        with:
          version: "11.25.0"
          run_install: false

      - name: 安装node环境
        uses: actions/setup-node@v7
        with:
          node-version: "22"
          cache: pnpm

      - name: 安装vitepress环境
        run: pnpm install --frozen-lockfile

      - name: 构建网站
        run: pnpm run check

      - name: 配置 GitHub Pages
        uses: actions/configure-pages@v4

      - name: 上传构建后的文件夹
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: 部署
        id: deployment
        uses: actions/deploy-pages@v4
